management:
    endpoints:
        web:
            exposure:
                include: "*"
server:
    servlet:
        context-path: /bidrag-hendelse-producer
    port: 8080

spring:
    kafka:
        bootstrap-servers: localhost:9092,localhost:9093
        properties:
            client:
                id: bidrag-hendelse-producer
            security.protocol: SASL_PLAINTEXT
            specific:
                avro.reader: true
            schema:
                registry.url: http://localhost:8081
            sasl:
                mechanism: PLAIN
                jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";
        producer:
            key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
            value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
            auto-offset-reset: earliest

app:
    topic: bidrag-registrert-journalpost-v1
