management:
    endpoints:
        web:
            exposure:
                include: "*"
server:
    servlet:
        context-path: /bidrag-hendelse-producer
    port: 8080

spring:
    kafka:
        bootstrap-servers: localhost:9092,localhost:9093
        properties:
            client:
                id: bidrag-hendelse-producer
            security.protocol: SASL_PLAINTEXT
            sasl:
                mechanism: PLAIN
                jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";
        producer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            auto-offset-reset: earliest

app:
    topic: bidrag-registrert-journalpost-v1
