apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-hendelse-producer
  namespace: {{ namespace }}
  labels:
    team: bidrag
spec:
  image: {{ image }}
  liveness:
    path: /bidrag-hendelse-producer/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-hendelse-producer/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - {{ ingress_preprod }}
    - {{ ingress_nais }}
