apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: bidrag-hendelse-producer
  namespace: {{ namespace }}
  labels:
    team: bidrag
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /bidrag-hendelse-producer/actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /bidrag-hendelse-producer/actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /bidrag-hendelse-producer/actuator/prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  ingresses:
    - https://bidrag-hendelse-producer.nais.adeo.no/
    - https://bidrag-hendelse-producer.prod-fss.nais.io
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvbidrag-dokument
        mountPath: /var/run/secrets/nais.io/srvbidrag-dokument
      - kvPath: /kv/prod/fss/bidrag-hendelse-producer/default
        mountPath: /var/run/secrets/nais.io/vault