management:
    endpoints:
        web:
            exposure:
                include: "*"
server:
    servlet:
        context-path: /bidrag-hendelse-producer
    port: 8080

spring:
    kafka:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_URL}
        properties:
            client:
                id: bidrag-hendelse-producer
            security.protocol: SASL_SSL
            specific:
                avro.reader: true
            schema:
                registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
            sasl:
                mechanism: PLAIN
                jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${SRVBIDRAG_DOKUMENT_USERNAME}" password="${SRVBIDRAG_DOKUMENT_PASSWORD}";
        producer:
            key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
            value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
            group-id: srvc01
            auto-offset-reset: earliest
kafka:
    topic: bidrag-registrert-journalpost-v1
